version: "3.8"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # RabbitMQ Server
      - "5672:5672"
      # Web Interface
      - "15672:15672"